# Generated by Django 3.2.12 on 2022-04-01 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Diak',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('oktatasi_azonosito', models.CharField(max_length=30)),
                ('nev', models.CharField(max_length=30)),
                ('felvettek_e', models.BooleanField()),
            ],
            options={
                'verbose_name': 'Diak',
                'verbose_name_plural': 'Diakok',
            },
        ),
    ]
